version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli@15.1.4
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build -c production
artifacts: 
  base-directory: dist/word_picker 
  files: 
    - '**/*' 